export const SET_NEXT_MONTH = "SET_NEXT_MONTH";
export const SET_LAST_MONTH = "SET_LAST_MONTH";
export const SET_TODAY = "SET_TODAY";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

export const CHANGE_SCHEDULE_FORM_STATUS = "CHANGE_SCHEDULE_FORM_STATUS";

export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
